# ==============================================================================
# COMMON SCRIPT HEADERS & FOOTERS
# ==============================================================================

# $1 = volume_name
# $2 = template_type
tpl_header() {
    local vol="$1"
    local type="$2"
    
    cat <<EOF
#!/bin/bash
# ======================================================
# BACKUP SCRIPT for: $vol
# Type: $type
# Auto-generated by DockVault
# ======================================================

set -e

# Colors
cyan=\$(tput setaf 6)
green=\$(tput setaf 2)
yellow=\$(tput setaf 3)
reset=\$(tput sgr0)

TIMESTAMP=\$(date +"%Y%m%d_%H%M%S")
TEMP_DIR="/tmp/backup_${vol}_\$TIMESTAMP"
mkdir -p "\$TEMP_DIR"

echo "\${cyan}[1/4] Starting backup for $vol at \$(date)\${reset}"
EOF
}

# $1 = remote
# $2 = gdrive_path
tpl_backup_footer() {
    local remote="$1"
    local path="$2"

    cat <<EOF

if [ -f "\$TEMP_DIR/\$ARCHIVE_NAME" ]; then
  FILE_SIZE=\$(du -h "\$TEMP_DIR/\$ARCHIVE_NAME" | cut -f1)
  echo "\${green}[2/4] Compression Complete. Archive Size: \$FILE_SIZE\${reset}"

  echo "\${cyan}[3/4] Uploading to Google Drive ($remote:$path)...\${reset}"
  
  if rclone copy "\$TEMP_DIR/\$ARCHIVE_NAME" "$remote:$path" --progress; then
     echo ""
     echo "\${green}[SUCCESS] Uploaded: \$ARCHIVE_NAME\${reset}"
  else
     echo "\${red}[ERROR] Rclone upload failed.\${reset}"
     exit 1
  fi
  rm -rf "\$TEMP_DIR"
else
  echo "\${red}[ERROR] Backup creation failed, file not found.\${reset}"
  exit 1
fi
EOF
}

# $1 = remote
# $2 = gdrive_path
# $3 = retention_days (e.g. 30d)
# $4 = min_files_count (e.g. 30)
tpl_retention_logic() {
    local remote="$1"
    local path="$2"
    local age="$3"
    local min_count="$4"

    cat <<EOF

# ======================================================
# RETENTION POLICY CHECK
# ======================================================
echo "\${cyan}[4/4] Checking Retention Policy (Max Age: $age, Min Files: $min_count)...\${reset}"

# Count total files in the remote folder
TOTAL_FILES=\$(rclone lsf "$remote:$path" --files-only | wc -l)

echo "Total backup files found: \$TOTAL_FILES"

if [ "\$TOTAL_FILES" -gt "$min_count" ]; then
  echo "Threshold met (> $min_count files). Pruning files older than $age..."
  
  # Run deletion
  # --min-age 30d means "files created more than 30 days ago"
  rclone delete "$remote:$path" --min-age $age -v
  
  echo "\${green}[CLEANUP] Old backups pruned.\${reset}"
else
  echo "\${yellow}[SKIP] File count (\$TOTAL_FILES) is below threshold ($min_count). No deletion performed.\${reset}"
fi

echo ""
echo "\${green}Backup Job Complete.\${reset}"
EOF
}

# $1 = volume_name
# $2 = remote
# $3 = gdrive_path
# $4 = restore_logic_block
tpl_restore_script() {
    local vol="$1"
    local remote="$2"
    local path="$3"
    local logic="$4"

    cat <<EOF
#!/bin/bash
# ======================================================
# RESTORE SCRIPT for: $vol
# Auto-generated by DockVault
# ======================================================

# Colors
cyan=\$(tput setaf 6)
green=\$(tput setaf 2)
yellow=\$(tput setaf 3)
red=\$(tput setaf 1)
reset=\$(tput sgr0)

echo "\${cyan}== RESTORE WIZARD: $vol ==\${reset}"
echo "\${red}WARNING: This will OVERWRITE data in the volume/database.\${reset}"
echo ""

# 1. Ask for Remote Folder
DEFAULT_PATH="$path"
read -e -p "Confirm Backup Folder Path (Default: \$DEFAULT_PATH): " INPUT_PATH
REMOTE_FOLDER="\${INPUT_PATH:-\$DEFAULT_PATH}"

# Remove quotes
REMOTE_FOLDER="\${REMOTE_FOLDER%\"}"
REMOTE_FOLDER="\${REMOTE_FOLDER#\"}"

echo ""
echo "\${cyan}Fetching file list from: $remote:\$REMOTE_FOLDER...\${reset}"

# 2. List Files & Interactive Select
mapfile -t FILE_LIST < <(rclone lsf "$remote:\$REMOTE_FOLDER" --files-only | sort -r)

if [ \${#FILE_LIST[@]} -eq 0 ]; then
  echo "\${red}No files found in $remote:\$REMOTE_FOLDER\${reset}"
  exit 1
fi

echo "Available Backups (Newest First):"
i=0
for file in "\${FILE_LIST[@]}"; do
  i=\$((i+1))
  echo "  [\$i] \$file"
done

echo ""
read -p "\${yellow}Select file number to restore: \${reset}" SELECTION

if [[ "\$SELECTION" =~ ^[0-9]+$ ]] && [ "\$SELECTION" -ge 1 ] && [ "\$SELECTION" -le "\${#FILE_LIST[@]}" ]; then
  idx=\$((SELECTION-1))
  SELECTED_FILE="\${FILE_LIST[\$idx]}"
else
  echo "\${red}Invalid selection.\${reset}"
  exit 1
fi

FULL_REMOTE_PATH="\$REMOTE_FOLDER/\$SELECTED_FILE"

echo ""
echo "-------------------------------------"
echo "Source: $remote:\$FULL_REMOTE_PATH"
echo "Target: $vol"
echo "-------------------------------------"
read -p "Type 'RESTORE' to confirm: " confirm

if [ "\$confirm" != "RESTORE" ]; then
  echo "Aborted."
  exit 1
fi

TEMP_DIR="/tmp/restore_${vol}_\$(date +%s)"
mkdir -p "\$TEMP_DIR"

echo "\${cyan}[INFO] Downloading backup file...\${reset}"
if ! rclone copy "$remote:\$FULL_REMOTE_PATH" "\$TEMP_DIR" --progress; then
  echo "\${red}[ERROR] Download failed.\${reset}"
  exit 1
fi

LOCAL_FILE=\$(find "\$TEMP_DIR" -type f | head -n 1)
FILENAME=\$(basename "\$LOCAL_FILE")

# === SPECIFIC RESTORE LOGIC ===
$logic
# ==============================

rm -rf "\$TEMP_DIR"
echo "\${green}[SUCCESS] Restore finished.\${reset}"
EOF
}
